application: xxxxxx
version: 1
runtime: go
api_version: go1

handlers:
- url: /manage
  script: _go_app
  login: required
- url: /invite
  script: _go_app
  login: required
- url: /lookup
  script: _go_app
  login: required
- url: /jot
  script: _go_app
  login: required
- url: /upload
  script: _go_app
  login: required
- url: /delete
  script: _go_app
  login: required  
- url: /coins
  script: _go_app
  login: required  
- url: /buy
  script: _go_app
- url: /rpc/v1
  script: _go_app
